[global]
error_log = /data/data/com.termux/files/home/debz_ai/logs/webui-fpm.log
pid = /data/data/com.termux/files/home/debz_ai/logs/webui-fpm.pid
daemonize = no

[www]
listen = /data/data/com.termux/files/home/debz_ai/logs/webui-fpm.sock
pm = dynamic
pm.max_children = 8
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 4
